➜  sage-9.5.beta0 git:(rtree_based_realset) ✗ ./sage -t src/sage/sets/real_set.py
too few successful tests, not using stored timings
Running doctests with ID 2021-09-11-17-54-28-ad53e607.
Git branch: rtree_based_realset
Using --optional=build,dochtml,homebrew,libspatialindex,pip,rtree,sage,sage_spkg
Doctesting 1 file.
sage -t --random-seed=0 src/sage/sets/real_set.py
**********************************************************************
File "src/sage/sets/real_set.py", line 66, in sage.sets.real_set
Failed example:
    type(RealSet_rtree(0,1) + RealSet(0.5,3))                                                                                    
Exception raised:
    Traceback (most recent call last):
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 718, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1137, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.sets.real_set[19]>", line 1, in <module>
        type(RealSet_rtree(Integer(0),Integer(1)) + RealSet(RealNumber('0.5'),Integer(3)))
    NameError: name 'RealSet_rtree' is not defined
**********************************************************************
File "src/sage/sets/real_set.py", line 68, in sage.sets.real_set
Failed example:
    A = RealSet_rtree(0,1) 
    B = RealSet(0.5,3) 
    C = B+A 
    type(C)                                                                                       
Exception raised:
    Traceback (most recent call last):
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 718, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1135, in compile_and_execute
        compiled = compiler(example)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 686, in compiler
        compileflags, 1)
      File "<doctest sage.sets.real_set[20]>", line 1
        A = RealSet_rtree(Integer(0),Integer(1))
                                                ^
    SyntaxError: multiple statements found while compiling a single statement
**********************************************************************
File "src/sage/sets/real_set.py", line 599, in sage.sets.real_set.InternalRealInterval.intersection
Failed example:
    A = RealSet(0,1) 
    B = RealSet(2,3) 
    C = B.intersection(A) 
    print(C, "with", type(C))                                                                     
Exception raised:
    Traceback (most recent call last):
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 718, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1135, in compile_and_execute
        compiled = compiler(example)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 686, in compiler
        compileflags, 1)
      File "<doctest sage.sets.real_set.InternalRealInterval.intersection[9]>", line 1
        A = RealSet(Integer(0),Integer(1))
                                          ^
    SyntaxError: multiple statements found while compiling a single statement
**********************************************************************
File "src/sage/sets/real_set.py", line 1836, in sage.sets.real_set.RealSet_rtree.__init__
Failed example:
    A = RealSet_rtree(0,1) 
    C = A.complement() 
    print(type(C), "with", C.rtree)                                                               
Exception raised:
    Traceback (most recent call last):
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 718, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1135, in compile_and_execute
        compiled = compiler(example)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 686, in compiler
        compileflags, 1)
      File "<doctest sage.sets.real_set.RealSet_rtree.__init__[0]>", line 1
        A = RealSet_rtree(Integer(0),Integer(1))
                                                ^
    SyntaxError: multiple statements found while compiling a single statement
**********************************************************************
File "src/sage/sets/real_set.py", line 1963, in sage.sets.real_set.RealSet_rtree.intersection
Failed example:
    A = RealSet_rtree(0,1) 
    B = RealSet_rtree(0.5,3) 
    C = A.intersection(B) 
    type(C)                                                                                       
Exception raised:
    Traceback (most recent call last):
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 718, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1135, in compile_and_execute
        compiled = compiler(example)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 686, in compiler
        compileflags, 1)
      File "<doctest sage.sets.real_set.RealSet_rtree.intersection[10]>", line 1
        A = RealSet_rtree(Integer(0),Integer(1))
                                                ^
    SyntaxError: multiple statements found while compiling a single statement
**********************************************************************
File "src/sage/sets/real_set.py", line 1968, in sage.sets.real_set.RealSet_rtree.intersection
Failed example:
    A = RealSet(0,1) 
    B = RealSet_rtree(0.5,3) 
    C = A.intersection(B) 
    type(C)                                                                                       
Exception raised:
    Traceback (most recent call last):
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 718, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1135, in compile_and_execute
        compiled = compiler(example)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 686, in compiler
        compileflags, 1)
      File "<doctest sage.sets.real_set.RealSet_rtree.intersection[11]>", line 1
        A = RealSet(Integer(0),Integer(1))
                                          ^
    SyntaxError: multiple statements found while compiling a single statement
**********************************************************************
File "src/sage/sets/real_set.py", line 1973, in sage.sets.real_set.RealSet_rtree.intersection
Failed example:
    A = RealSet(0,1) 
    B = RealSet_rtree(0.5,3) 
    C = B.intersection(A) 
    type(C)                                                                                       
Exception raised:
    Traceback (most recent call last):
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 718, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1135, in compile_and_execute
        compiled = compiler(example)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 686, in compiler
        compileflags, 1)
      File "<doctest sage.sets.real_set.RealSet_rtree.intersection[12]>", line 1
        A = RealSet(Integer(0),Integer(1))
                                          ^
    SyntaxError: multiple statements found while compiling a single statement
**********************************************************************
File "src/sage/sets/real_set.py", line 1978, in sage.sets.real_set.RealSet_rtree.intersection
Failed example:
    A = RealSet(0,1) 
    B = RealSet_rtree(2,3) 
    C = B.intersection(A) 
    print(C, "with", type(C))                                                                     
Exception raised:
    Traceback (most recent call last):
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 718, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1135, in compile_and_execute
        compiled = compiler(example)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 686, in compiler
        compileflags, 1)
      File "<doctest sage.sets.real_set.RealSet_rtree.intersection[13]>", line 1
        A = RealSet(Integer(0),Integer(1))
                                          ^
    SyntaxError: multiple statements found while compiling a single statement
**********************************************************************
File "src/sage/sets/real_set.py", line 1983, in sage.sets.real_set.RealSet_rtree.intersection
Failed example:
    A = RealSet_rtree(-infinity, infinity) 
    C = A.complement() 
    print(type(C), "with", C.rtree)                                                               
Exception raised:
    Traceback (most recent call last):
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 718, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1135, in compile_and_execute
        compiled = compiler(example)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 686, in compiler
        compileflags, 1)
      File "<doctest sage.sets.real_set.RealSet_rtree.intersection[14]>", line 1
        A = RealSet_rtree(-infinity, infinity)
                                              ^
    SyntaxError: multiple statements found while compiling a single statement
**********************************************************************
File "src/sage/sets/real_set.py", line 1987, in sage.sets.real_set.RealSet_rtree.intersection
Failed example:
    type(RealSet_rtree(-infinity, infinity).complement())                                                           
Exception raised:
    Traceback (most recent call last):
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 718, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/binshuaiwang/Research/sage-9.5.beta0/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1137, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.sets.real_set.RealSet_rtree.intersection[15]>", line 1, in <module>
        type(RealSet_rtree(-infinity, infinity).complement())
    NameError: name 'RealSet_rtree' is not defined
**********************************************************************
4 items had failures:
   2 of  22 in sage.sets.real_set
   1 of  11 in sage.sets.real_set.InternalRealInterval.intersection
   1 of   2 in sage.sets.real_set.RealSet_rtree.__init__
   6 of  17 in sage.sets.real_set.RealSet_rtree.intersection
    [281 tests, 10 failures, 0.30 s]
----------------------------------------------------------------------
sage -t --random-seed=0 src/sage/sets/real_set.py  # 10 doctests failed
----------------------------------------------------------------------
Total time for all tests: 0.4 seconds
    cpu time: 0.3 seconds
    cumulative wall time: 0.3 seconds
Pytest is not installed, skip checking tests that rely on it.
